SELECT DISTINCT
    CLI.CODIGO,
    CLI.RAZAO

FROM CLIFORN CLI

WHERE CLI.CODIGO IN (
        SELECT CODCLIFORN FROM MOVIMENTACOES 
        WHERE CODTIPOMOV IN ('2.2.02', '2.2.40')
)
AND CLI.CF_LIM_FAT <> ''

ORDER BY RAZAO