SELECT DISTINCT   
	MOV.IDMOV,
	MOV.CODIGO,                                     
	MOV.DATAEMISSAO,
	MOV.DATAENTREGA,
	MOV.DATAENTRADA,
	MOV.PESOBRUTO,
	MOV.PESOLIQUIDO,
	MOV.OBSERVACOES,
	MOV.PLACAVEICULO,
	MOV.PESOBRUTO, 
	MOV.QTDEVOLUMES,
	FUNC1.NOME SOLICITANTE,                                                                       
	(SELECT GCENTROCUSTO.NOME FROM GCENTROCUSTO WHERE CODIGO = MOV.CODCENTROCUSTO)AS CENTROCUSTO,
	(SELECT TOP 1 RAZAO FROM CLIFORN WHERE CODIGO = MOV.MOTORISTA) AS MOTORISTA,
	(SELECT TOP 1 CASE CGCCFO WHEN '   .   .   -  ' THEN '' ELSE CGCCFO END	
		FROM CLIFORN WHERE CODIGO = MOV.MOTORISTA) AS MOTORISTA_CPF, 
	CASE MOV.TIPOFRETE 
		WHEN 0 THEN 'CIF'
		WHEN 1 THEN 'FOB' ELSE '' 
	END AS TIPO_FRETE,
	TRANS.RAZAO AS TRANSPORTADOR,
	TRANS.CNPJ  AS CNPJ_TRANSP,
	MOV.ESPECIE,                                           
	TIPOMOV.DESCRICAO ,           
	CLIFORN.NOMEFANTASIA,
	CLIFORN.RAZAO,                                     
	CLIFORN.RUA, 
	CLIFORN.NUMERO, 
	CLIFORN.BAIRRO, 
	CLIFORN.CEP, 
	CLIFORN.FONE,
	CLIFORN.FAX,
	CLIFORN.EMAIL,           
	CLIFORN.INSCEST,
	TRANS.NOMEFANTASIA TRANSPORTADORA,
	REDESP.NOMEFANTASIA TRANSP_REDESP,                                                                                           
	(SELECT CASE WHEN CLIFORN.PESFISOUJUR LIKE 'F%' THEN 
		CLIFORN.CGCCFO
	ELSE CLIFORN.CNPJ END) CPF_CNPJ, 
	CID.NOME AS CIDADE, 
	G_UF.IDENTIFICADOR UF, 
	REP.NOME REPRESENTANTE,
	CC.NOMECONTATO, MOV.CAMPOLIVRE1,
	(SELECT DESCRICAO 
		FROM CONDICOESPAGAMENTO
		WHERE CODIGO = MOV.CODCONDICOESPAGAMENTO) CONDPAG,
	(SELECT C.NOME FROM COLABORADOR C
		JOIN  MOVIMENTACOES_BLOQUEIO MB
          ON MB.USUARIO_LIBERACAO = C.CODIGO
	WHERE MB.CODIGO_MOVIMENTACAO = MOV.CODIGO) AS USUARIO_APROVACAO,
	MOV.OBSERVACOES_MOVIMENTO                    
           
FROM MOVIMENTACOES MOV 
	
	LEFT JOIN TIPOMOVIMENTO TIPOMOV 
		ON TIPOMOV.CODTIPOMOV = MOV.CODTIPOMOV   
	
	LEFT JOIN CLIFORN 
		ON CLIFORN.CODIGO = MOV.CODCLIFORN
		 
	LEFT JOIN G_MUNICIPIOS CID 
		ON CID.CODIGO = CLIFORN.CODIGO_MUNICIPIOS
		 
	LEFT JOIN G_UF 
		ON G_UF.CODIGO = CID.CODIGO_UF

	LEFT JOIN REPRESENTANTES REP 
		ON REP.CODIGO = MOV.CODREPRESENTANTE

	LEFT JOIN CLIFORN TRANS
		ON TRANS.CODIGO = MOV.CODTRANSPORTADORA

	LEFT JOIN CLIFORN REDESP
		ON REDESP.CODIGO = MOV.CODREDESPACHO

	LEFT JOIN CONTATOSCFO CC    
		ON CC.CODCLIFORN = CLIFORN.CODIGO
	
	LEFT JOIN COLABORADOR FUNC1                      
		ON FUNC1.CODIGO = MOV.CODFUNCIONARIO1

WHERE 1=1
--WHERE MOV.CODIGO = :CODIGO