SELECT DISTINCT
	PRD.IDPRD,
	PRD.NOME AS PRODUTO,                                                         
	UND.SIMBOLO AS UND,      
	ITM.QUANTIDADE,
	ITM.IDENTIFICADOR_PRODUTO,                                                                             
	(PRD.CAMPOLIVRE1 + '-' + PRD.CAMPOLIVRE2 + '-' + PRD.CAMPOLIVRE3) LOCALIZACAO,
	PRD.PESOLIQUIDO,
	PRD.PESOBRUTO,
	PRD.CODIGO, 
    --(SELECT LP.CODIGO
    --FROM LOTEPRODUTO LP 
    --WHERE LP.CODPRODUTO = PRD.CODIGO) CODLOTE, 
	ITM.CAMPOLIVRE2 CAMPO_OBS,
	ITM.VALORUNITARIO,
	ITM.VALORTOTAL,
	(SELECT GP.DESCRICAO FROM GRUPOPRODUTO GP
		WHERE GP.CODIGO = PRD.CODGRUPO) AS NOME_GRUPO,
	CAST((ITM.QUANTIDADE / 
		ISNULL(PRD.FATOR_CONVERSAO_PAUTA,1) ) AS NUMERIC(14,2)) QTDE_CAIXA,
	ITM.CODIGO COD_ITEM,
	ITM.CODMOV

FROM ITENSMOVIMENTACOES ITM
	
	LEFT JOIN MOVIMENTACOES MOV  
		ON MOV.CODIGO  = ITM.CODMOV  
	
	LEFT JOIN GPRODUTO PRD 
		ON PRD.CODIGO = ITM.CODPRODUTO 
	
	LEFT JOIN UNIDADES UND 
		ON UND.CODIGO = PRD.CODUNDCONTROLE
	
	LEFT JOIN LOTEPRODUTOMOVIMENTACOES LPRD
		ON LPRD.CODITENSMOVIMENTACOES = ITM.CODIGO

WHERE 1=1
--ITM.CODMOV = :CODIGO