SELECT
    ITM.CODIGO,
	ITM.IDPRODUTO,
	ITM.DESCPRODUTO,
	CAST(SUM(ITM.QUANTIDADE) AS FLOAT) AS QUANTIDADE

FROM ITENSMOVIMENTACOES ITM

	INNER JOIN MOVIMENTACOES MOV
		ON MOV.CODIGO = ITM.CODMOV

WHERE MOV.IDMOV <> ''
	AND MOV.STATUS <> 6
	AND MOV.CODTIPOMOV = '2.1.02'


    [qryProdutos."IDPRODUTO"]