SELECT
    UPPER(C.NOME) COLIGADA,

    UPPER(F.RAZAOSOCIAL) RAZAOSOCIAL,
    UPPER(F.NOMEFANTASIA) NOMEFANTASIA,

    C.CNPJ,
    F.INSCRICAOESTADUAL,    
	
    UPPER(F.RUA) RUA,
    F.NUMERO,	   
    UPPER(F.BAIRRO) BAIRRO,
    F.CEP,
    
    UPPER(M.NOME) CIDADE,
    UPPER(U.IDENTIFICADOR) UF,

    F.TELEFONE,
    F.EMAIL	

FROM COLIGADA C
	
    INNER JOIN FILIAL F 
        ON C.CODIGO = F.CODCOLIGADA
    LEFT JOIN G_MUNICIPIOS M 
        ON M.CODIGO = F.CODIGO_MUNICIPIOS
    LEFT JOIN G_UF U 
        ON U.CODIGO = M.CODIGO_UF

WHERE F.CODIGO = 1