SELECT DISTINCT
	LAN.STATUS,
	CASE
		WHEN LAN.STATUS = 'ABERTO' THEN 
			CAST(1 AS INTEGER)
		WHEN LAN.STATUS = 'ADIANTAMENTO ABERTO' THEN
			CAST(2 AS INTEGER)
		WHEN LAN.STATUS = 'CANCELADO' THEN
			CAST(3 AS INTEGER)
		WHEN LAN.STATUS = 'CRÉDITO EM ABERTO' THEN
			CAST(4 AS INTEGER)
		WHEN LAN.STATUS = 'QUITADO' THEN
			CAST(5 AS INTEGER)
		WHEN LAN.STATUS = 'QUITADO PARCIALMENTE' THEN
			CAST(6 AS INTEGER)
		WHEN LAN.STATUS = 'QUITADO POR ACORDO' THEN
			CAST(7 AS INTEGER)		
	END AS CODIGO

FROM LANCAMENTOS LAN
WHERE LAN.STATUS NOT IN ('CANCELADO', 'QUITADO POR ACORDO')                                                          

ORDER BY LAN.STATUS