SELECT
	CODIGO,
	CODTIPOMOV,
	CODTIPOMOV + ' - ' + LTRIM(UPPER(DESCRICAO)) DESCRICAO,
	ISNULL(CODTIPODOC, 0) CODTIPODOC

FROM TIPOMOVIMENTO

WHERE CODIGO IN (
    SELECT DISTINCT CODIGO_TIPOMOVIMENTO FROM MOVIMENTACOES)

ORDER BY CODTIPOMOV