USE CANTONORTE
SET DATEFORMAT DMY                                                 

SELECT DISTINCT
    
	UPPER(LAN.PAGREC) PAGREC,
	LAN.STATUS,

	-- CODIGOS
    LAN.CODIGO,
	MOV.CODIGO,
	ISNULL(MOV.IDMOV, 'LAN. D. FINAN') AS IDMOV,	
    LAN.NUMERODOCUMENTO AS NUMERODOC,

	-- TIPO DE LANCAMENTO
	ISNULL(CAST(LAN.CODTIPODOC AS VARCHAR(10)) + ' - ' 
        + TPD.DESCRICAO, 'NÃO INFORMADO') AS TIPOLANC,

	-- TIPO DE MOVIMENTO
	CASE WHEN LAN.CODMOV IS NOT NULL THEN
		MOV.CODTIPOMOV + ' - ' + UPPER(TMV.DESCRICAO)
	ELSE 'LAN. D. FINAN' END AS TIPOMOV,

	-- TIPO OU FORMA DE PAGAMENTO
    ISNULL(CAST(PAG.CODTIPOPGTO AS VARCHAR(5)) + ' - '
        + TPG.DESCRICAO, 'NÃO INFORMADO') AS TIPOPAG,
	
	-- EVENTO FINANCEIRO
	ISNULL(CAST(LAN.EVENTOFINANCEIRO AS VARCHAR(10)) + ' - ' 
        + EVF.DESCRICAO, 'NÃO INFORMADO') AS EVENTOFINANCEIRO,	
	
	-- CLIENTE OU FORNECEDOR
	UPPER(LTRIM(CLI.RAZAO)) +' / '+ 
        CASE WHEN CLI.PESFISOUJUR LIKE '%FÍSICA%' THEN 
            'CPF: ' + CLI.CGCCFO
		ELSE 'CNPJ: ' + CLI.CNPJ END AS CLIFORN,
	
	-- CENTRO DE CUSTOS
	ISNULL(CASE WHEN LAN.CENTROCUSTO IS NOT NULL THEN	
			CAST(LAN.CENTROCUSTO AS VARCHAR(10)) + ' - '
			
			ELSE CASE WHEN MOV.CODCENTROCUSTO IS NOT NULL THEN
				CAST(MOV.CODCENTROCUSTO AS VARCHAR(10)) + ' - '
		
				ELSE CASE WHEN MVR.CODIGO_CENTROCUSTO IS NOT NULL THEN
					CAST(MVR.CODIGO_CENTROCUSTO AS VARCHAR(10)) + ' - '				
				END	
			END
		END
    + UPPER(GCC.ABREVIATURA) + ' - ' 
    + UPPER(GCC.NOME), 'NÃO INFORMADO') AS CENTROCUSTO,

	-- DATAS
	LAN.DATAGERACAO AS DGL,
	MOV.DATAGERACAO AS DGM,
	LAN.DATAVENCIMENTO,
	PAG.DATA AS DATAPAGAMENTO,		

	-- VALORES
	ISNULL(SUM(LAN.VALORORIGINAL), 0) AS VALORORIGINAL,
	ISNULL(SUM(LAN.ACRESCIMO), 0) AS VALORACRESCIMO,
	ISNULL(SUM(LAN.DESCONTO), 0) AS VALORDESCONTO,	
		
	-- VALOR FINAL DO LANCAMENTO
	CASE WHEN TMV.USA_RATEIO_CCUSTO = 1 THEN
		ISNULL(MVR.PERCENTUAL * LAN.VALORORIGINAL / 100, 0)
	ELSE ISNULL(LAN.VALORORIGINAL, 0) END AS VALORFINAL,
	
	-- VALOR FINAL DO PAGAMENTO CASO TENHA
	CASE WHEN TMV.USA_RATEIO_CCUSTO = 1 THEN
		ISNULL((AGB.VALOR) * MVR.PERCENTUAL / 100, 0)
	ELSE ISNULL((AGB.VALOR), 0) END AS VALOR_PAG_REC

FROM LANCAMENTOS LAN

	LEFT JOIN CLIFORN CLI 
		ON CLI.CODIGO = LAN.CODFORNECEDOR
	
	LEFT JOIN MOVIMENTACOES MOV 
		ON MOV.CODIGO = LAN.CODMOV

	LEFT JOIN MOVIMENTACOES_RATEIO MVR
		ON MVR.CODIGO_MOVIMENTACOES = LAN.CODMOV

	INNER JOIN GCENTROCUSTO GCC
		ON GCC.CODIGO = LAN.CENTROCUSTO
		    OR GCC.CODIGO = MOV.CODCENTROCUSTO
		    OR GCC.CODIGO = MVR.CODIGO_CENTROCUSTO	

	LEFT JOIN TIPODOC TPD 
		ON TPD.CODIGO = LAN.CODTIPODOC

	LEFT JOIN I_EVENTOFINANCEIRO EVF
		ON EVF.CODIGO = LAN.EVENTOFINANCEIRO	

	LEFT JOIN TIPOMOVIMENTO TMV 
		ON TMV.CODIGO = MOV.CODIGO_TIPOMOVIMENTO	

	LEFT OUTER JOIN AGRUPADORBAIXAS AGB
		ON AGB.CODLANCAMENTO = LAN.CODIGO

	LEFT OUTER JOIN PAGAMENTOS PAG
		ON PAG.CODIGO = AGB.CODPAGAMENTO

	LEFT OUTER JOIN TIPOPAGAMENTO TPG
		ON TPG.CODIGO = PAG.CODTIPOPGTO 
		OR TPG.CODIGO = LAN.CODIGO_TIPOPAGAMENTO

WHERE LAN.STATUS NOT IN ('QUITADO POR ACORDO', 'CANCELADO')

GROUP BY

LAN.PAGREC,
LAN.STATUS,

LAN.CODIGO,
LAN.CODMOV,
MOV.CODIGO,
MOV.IDMOV,
LAN.NUMERODOCUMENTO,

LAN.CODTIPODOC,
TPD.DESCRICAO,

MOV.CODTIPOMOV,
TMV.DESCRICAO,

PAG.CODTIPOPGTO,
TPG.DESCRICAO,

LAN.EVENTOFINANCEIRO,
EVF.DESCRICAO,

CLI.CODIGO,
CLI.RAZAO,
CLI.PESFISOUJUR,
CLI.CGCCFO,
CLI.CNPJ,

LAN.CENTROCUSTO,
MOV.CODCENTROCUSTO,
MVR.CODIGO_CENTROCUSTO,

GCC.ABREVIATURA,
GCC.NOME,

LAN.DATAGERACAO,
MOV.DATAGERACAO,
LAN.DATAVENCIMENTO,
PAG.DATA,

LAN.VALORORIGINAL,
LAN.ACRESCIMO,
LAN.DESCONTO,

TMV.USA_RATEIO_CCUSTO,
MVR.PERCENTUAL,

AGB.VALOR